.TH wpmstats 1 "August 2018" sirjofri "WPM statistics"
.SH NAME
wpmstats.awk, wpmtable.awk \- prints statistics about your wpm usage.
.SH SYNOPSIS
.B wpmstats.awk <\fI~/.wpm.csv
.br
.B wpmtable.awk <\fI~/.wpm.csv
.SH DESCRIPTION
.B wpmstats.awk
prints average statistics about your typing sessions.
.PP
.B wpmtable.awk
prettyprints the relevant information in a table.
.SH AUTHOR
This package is created by sirjofri.
.SH SEE ALSO
.BR awk (1)
